apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lfsr-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/DeLaMercedSorianoUriel/LFSRSoft"
    targetRevision: Develop
    path: proyecto-lfsrsoft/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: lfsrsoft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
