apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: lfsrsoft
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASSWORD: cHJveWVjdG9ERVY=
  DB_NAME: TEZTUg==
  AES_KEY: S2w1YldLcVdPL253ODRDd2FDWnFOYnBGelg3WVJMdVBONXk4aXQ2L0cxVT0=
